/// gas_regression.rs
///
/// Measures Soroban CPU instruction consumption for each tracked contract
/// function and writes the results to gas-measurements.json in the workspace
/// root.
///
/// Run via:
///   cargo test --test gas_regression -- --nocapture
///
/// The file produced is then consumed by:
///   node scripts/check-gas-regression.js \
///     --baseline gas-baselines.json \
///     --measured  gas-measurements.json
///
/// Functions tracked:
///   initialize, deposit, withdraw, harvest, pause, unpause

#![cfg(test)]

use soroban_sdk::{
    testutils::{Address as _, Budget},
    Address, Env,
};

soroban_sdk::contractimport!(
    file = "target/wasm32-unknown-unknown/release/aura_vault.wasm"
);

// ── Helpers ──────────────────────────────────────────────────────────────────

fn setup() -> (Env, AuraVaultClient<'static>, Address, Address) {
    let env = Env::default();
    env.mock_all_auths();

    let contract_id = env.register_contract_wasm(None, WASM);
    let client = AuraVaultClient::new(&env, &contract_id);

    let token_admin = Address::generate(&env);
    let underlying = env.register_stellar_asset_contract_v2(token_admin.clone());
    let token_client =
        soroban_sdk::token::StellarAssetClient::new(&env, &underlying.address());

    token_client.mint(&token_admin, &10_000_000_000_i128);

    (env, client, token_admin, underlying.address())
}

fn measure<F: FnOnce()>(env: &Env, f: F) -> u64 {
    env.budget().reset_default();
    f();
    env.budget().cpu_instruction_count()
}

// ── Measurement test ──────────────────────────────────────────────────────────

#[test]
fn write_gas_measurements() {
    let (env, client, admin, token) = setup();

    // initialize
    let init_cpu = measure(&env, || {
        client.initialize(&admin, &token);
    });

    // deposit
    let deposit_cpu = measure(&env, || {
        client.deposit(&admin, &1_000_000_i128);
    });

    // harvest — mint extra tokens first so keeper can inject yield
    {
        use soroban_sdk::token::StellarAssetClient;
        let tc = StellarAssetClient::new(&env, &token);
        tc.mint(&admin, &500_000_i128);
    }
    let harvest_cpu = measure(&env, || {
        client.harvest(&admin, &500_000_i128);
    });

    // withdraw — burn remaining shares
    let shares = client.balance_of(&admin);
    let withdraw_cpu = measure(&env, || {
        client.withdraw(&admin, &shares);
    });

    // pause / unpause
    let pause_cpu = measure(&env, || {
        client.pause();
    });
    let unpause_cpu = measure(&env, || {
        client.unpause();
    });

    // ── Emit JSON ─────────────────────────────────────────────────────────────
    let json = format!(
        "{{\n  \"_comment\": \"Auto-generated by gas_regression.rs — do not edit manually.\",\n  \"measurements\": {{\n    \"initialize\": {initialize},\n    \"deposit\":    {deposit},\n    \"withdraw\":   {withdraw},\n    \"harvest\":    {harvest},\n    \"pause\":      {pause},\n    \"unpause\":    {unpause}\n  }}\n}}",
        initialize = init_cpu,
        deposit    = deposit_cpu,
        withdraw   = withdraw_cpu,
        harvest    = harvest_cpu,
        pause      = pause_cpu,
        unpause    = unpause_cpu,
    );

    let out_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace root exists")
        .join("gas-measurements.json");

    std::fs::write(&out_path, &json).expect("failed to write gas-measurements.json");

    println!("\n=== Gas measurements written to {} ===\n{}", out_path.display(), json);
}
